name: build
on:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout project sources
          uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
          run: ./gradlew build
  test:
    needs: build
    runs-on: ubuntu_latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew test



