version: '2.1'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=parts_shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres