spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parts_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES

