spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parts_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
server:
  error:
    include-message: on-param
jwt:
  secret: ${JWT_TOKEN_SECRET}
#  access token lifetime in minutes
  access-token-lifetime: 10
#  refresh token lifetime in hours
  refresh-token-lifetime: 1
logging:
  level:
    org:
      springframework:
        security: DEBUG

redis:
  host: localhost
  port: 6379