/*
 * This file is generated by jOOQ.
 */
package structure.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import structure.tables.SessionHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SessionHistoryRecord extends UpdatableRecordImpl<SessionHistoryRecord> implements Record2<LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.session_history.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.session_history.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(0);
    }

    /**
     * Setter for <code>public.session_history.message</code>.
     */
    public void setMessage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.session_history.message</code>.
     */
    public String getMessage() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<LocalDateTime> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<LocalDateTime, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<LocalDateTime, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<LocalDateTime> field1() {
        return SessionHistory.SESSION_HISTORY.TIME;
    }

    @Override
    public Field<String> field2() {
        return SessionHistory.SESSION_HISTORY.MESSAGE;
    }

    @Override
    public LocalDateTime component1() {
        return getTime();
    }

    @Override
    public String component2() {
        return getMessage();
    }

    @Override
    public LocalDateTime value1() {
        return getTime();
    }

    @Override
    public String value2() {
        return getMessage();
    }

    @Override
    public SessionHistoryRecord value1(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public SessionHistoryRecord value2(String value) {
        setMessage(value);
        return this;
    }

    @Override
    public SessionHistoryRecord values(LocalDateTime value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionHistoryRecord
     */
    public SessionHistoryRecord() {
        super(SessionHistory.SESSION_HISTORY);
    }

    /**
     * Create a detached, initialised SessionHistoryRecord
     */
    public SessionHistoryRecord(LocalDateTime time, String message) {
        super(SessionHistory.SESSION_HISTORY);

        setTime(time);
        setMessage(message);
    }
}
