/*
 * This file is generated by jOOQ.
 */
package structure;


import structure.tables.TraceHistory;
import structure.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.trace_history</code>.
     */
    public static final TraceHistory TRACE_HISTORY = TraceHistory.TRACE_HISTORY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
