/*
 * This file is generated by jOOQ.
 */
package structure;


import structure.tables.SessionHistory;
import structure.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>public.session_history</code>.
     */
    public static final SessionHistory SESSION_HISTORY = SessionHistory.SESSION_HISTORY;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
