/*
 * This file is generated by jOOQ.
 */
package structure.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import structure.Keys;
import structure.Public;
import structure.tables.records.LogsRecord;

import java.time.LocalDateTime;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Logs extends TableImpl<LogsRecord> {

    /**
     * The reference instance of <code>public.logs</code>
     */
    public static final Logs LOGS = new Logs();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>public.logs.time</code>.
     */
    public final TableField<LogsRecord, LocalDateTime> TIME = createField(DSL.name("time"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");
    /**
     * The column <code>public.logs.message</code>.
     */
    public final TableField<LogsRecord, String> MESSAGE = createField(DSL.name("message"), SQLDataType.VARCHAR, this, "");

    private Logs(Name alias, Table<LogsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Logs(Name alias, Table<LogsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.logs</code> table reference
     */
    public Logs(String alias) {
        this(DSL.name(alias), LOGS);
    }

    /**
     * Create an aliased <code>public.logs</code> table reference
     */
    public Logs(Name alias) {
        this(alias, LOGS);
    }

    /**
     * Create a <code>public.logs</code> table reference
     */
    public Logs() {
        this(DSL.name("logs"), null);
    }

    public <O extends Record> Logs(Table<O> child, ForeignKey<O, LogsRecord> key) {
        super(child, key, LOGS);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LogsRecord> getRecordType() {
        return LogsRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LogsRecord> getPrimaryKey() {
        return Keys.LOGS_PKEY;
    }

    @Override
    public Logs as(String alias) {
        return new Logs(DSL.name(alias), this);
    }

    @Override
    public Logs as(Name alias) {
        return new Logs(alias, this);
    }

    @Override
    public Logs as(Table<?> alias) {
        return new Logs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Logs rename(String name) {
        return new Logs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Logs rename(Name name) {
        return new Logs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Logs rename(Table<?> name) {
        return new Logs(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<LocalDateTime, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super LocalDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
