/*
 * This file is generated by jOOQ.
 */
package structure.tables;


import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import structure.Keys;
import structure.Public;
import structure.tables.records.ProductRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Product extends TableImpl<ProductRecord> {

    /**
     * The reference instance of <code>public.product</code>
     */
    public static final Product PRODUCT = new Product();
    private static final long serialVersionUID = 1L;
    /**
     * The column <code>public.product.id</code>.
     */
    public final TableField<ProductRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");
    /**
     * The column <code>public.product.name</code>.
     */
    public final TableField<ProductRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR.nullable(false), this, "");
    /**
     * The column <code>public.product.description</code>.
     */
    public final TableField<ProductRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR, this, "");
    /**
     * The column <code>public.product.cost</code>.
     */
    public final TableField<ProductRecord, Double> COST = createField(DSL.name("cost"), SQLDataType.DOUBLE, this, "");
    /**
     * The column <code>public.product.status</code>.
     */
    public final TableField<ProductRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false), this, "");
    /**
     * The column <code>public.product.seller_id</code>.
     */
    public final TableField<ProductRecord, Integer> SELLER_ID = createField(DSL.name("seller_id"), SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column <code>public.product.buyer_id</code>.
     */
    public final TableField<ProductRecord, Integer> BUYER_ID = createField(DSL.name("buyer_id"), SQLDataType.INTEGER, this, "");
    private transient Users _productSellerIdFkey;
    private transient Users _productBuyerIdFkey;

    private Product(Name alias, Table<ProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private Product(Name alias, Table<ProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.product</code> table reference
     */
    public Product(String alias) {
        this(DSL.name(alias), PRODUCT);
    }

    /**
     * Create an aliased <code>public.product</code> table reference
     */
    public Product(Name alias) {
        this(alias, PRODUCT);
    }

    /**
     * Create a <code>public.product</code> table reference
     */
    public Product() {
        this(DSL.name("product"), null);
    }

    public <O extends Record> Product(Table<O> child, ForeignKey<O, ProductRecord> key) {
        super(child, key, PRODUCT);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductRecord> getRecordType() {
        return ProductRecord.class;
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ProductRecord, Integer> getIdentity() {
        return (Identity<ProductRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProductRecord> getPrimaryKey() {
        return Keys.PRODUCT_PKEY;
    }

    @Override
    public List<ForeignKey<ProductRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRODUCT__PRODUCT_SELLER_ID_FKEY, Keys.PRODUCT__PRODUCT_BUYER_ID_FKEY);
    }

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>product_seller_id_fkey</code> key.
     */
    public Users productSellerIdFkey() {
        if (_productSellerIdFkey == null)
            _productSellerIdFkey = new Users(this, Keys.PRODUCT__PRODUCT_SELLER_ID_FKEY);

        return _productSellerIdFkey;
    }

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>product_buyer_id_fkey</code> key.
     */
    public Users productBuyerIdFkey() {
        if (_productBuyerIdFkey == null)
            _productBuyerIdFkey = new Users(this, Keys.PRODUCT__PRODUCT_BUYER_ID_FKEY);

        return _productBuyerIdFkey;
    }

    @Override
    public Product as(String alias) {
        return new Product(DSL.name(alias), this);
    }

    @Override
    public Product as(Name alias) {
        return new Product(alias, this);
    }

    @Override
    public Product as(Table<?> alias) {
        return new Product(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(String name) {
        return new Product(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Name name) {
        return new Product(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Table<?> name) {
        return new Product(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, String, Double, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Integer, ? super String, ? super String, ? super Double, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Integer, ? super String, ? super String, ? super Double, ? super String, ? super Integer, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
