name: build
on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2

      - name: Build database image
        run: docker-compose up -d

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Show db logs
        run: docker logs db
        shell: bash

      - name: Run build with Gradle Wrapper
        run: ./gradlew test
  cleaner:
    runs-on: self-hosted
    needs: test
    if: ${{ always() }}
    steps:
      - name: db stopper
        run: docker stop db
        shell: bash
      - name: db cleaner
        run: docker rm -f -v db
        shell: bash
      - name: redis stopper
        run: docker stop redis
        shell: bash
      - name: redis cleaner
        run: docker rm -f -v redis
        shell: bash

  deploy:
    runs-on: self-hosted
    needs:
      - test
      - cleaner
    if: needs.test.result == 'success'
    steps:
      - name: Stopping old version
        run: |
          [ -d "$HOME/shop/" ] && cd ~/shop && sh clear.sh || 2>/dev/null

      - name: Copy files to deploy folder
        run: |
          cp -r ./ ~/shop 

      - name: starting new screen
        run: |
          cd ~/shop && sudo docker-compose -f ~/shop/docker-compose-prod.yml up -d && AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} JWT_TOKEN_SECRET=${{ secrets.JWT_TOKEN_SECRET }} screen -dmS shop ./gradlew bootRun --args='--spring.profiles.active=prod' &

