name: build
on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2

      - name: Build database image
        run: sudo docker-compose build
      - name: Start database
        run: sudo docker-compose start
      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Show db logs
        run: docker logs db
        shell: bash
      - name: Run build with Gradle Wrapper
        run: ./gradlew test



