name: build
on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Build docker images
        run: docker-compose up



