name: build
on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2

      - name: Build docker images
        run: sudo docker-compose up
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      - name: Run build with Gradle Wrapper
        run: ./gradlew test



