name: build
on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2

      - name: Build database image
        run: docker-compose up -d

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Show db logs
        run: docker logs db
        shell: bash

      - name: Run build with Gradle Wrapper
        run: ./gradlew test
  cleaner:
    runs-on: self-hosted
    needs: test
    if: ${{ always() }}
    steps:
      - name: db stopper
        run: docker stop db
        shell: bash
      - name: db cleaner
        run: docker rm -f -v db
        shell: bash
      - name: redis stopper
        run: docker stop redis
        shell: bash
      - name: redis cleaner
        run: docker rm -f -v redis
        shell: bash



