name: build
on:
  push

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gralde
        uses: gradle/gradle-build-action@v2

      - name: Build database image
        run: sudo docker-compose up -d

      - name: Sleep for 5 seconds
        run: sleep 5s
        shell: bash

      - name: Show db logs
        run: sudo docker logs db
        shell: bash

      - name: Run build with Gradle Wrapper
        run: ./gradlew test



